language: go
os:
  - linux
  - osx
go:
  # 1.10 & 1.11 are now best-effort; we recommend 1.12
  # - "1.10" gofmt changes mean 1.10 fails testing
  - "1.11"
  - "1.12"

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org make travis-ci
